### ISSUE TITLE
Release for 4.7

### ISSUE THREAD

**Issue by shawnholt** [sgladstone/com.pogstone.fancytokens#14]
Any known issues?  Likely issues?

**Comment by twomice** [comment]
FWIW, there are at present at least some sites using this extension under CiviCRM 4.7. See https://stats.civicrm.org/json/ext/com.pogstone.fancytokens.json

**Comment by sgladstone** [comment]
Per the page at stats.civicrm.org, there are already 63 sites using this extension under CiviCRM 4.7.x. Since  no issues have been reported, I consider this extension compatible with 4.7, and updated the info.xml to reflect this.
