### ISSUE TITLE
Tag the new release?

### ISSUE THREAD

**Issue by PalanteJon** [sgladstone/com.pogstone.fancytokens#15]
Hi Sarah,

I noticed that the extension directory wasn't showing version 3.6, so I looked into why.  The release isn't tagged in git.

If you've got your master branch checked out on your computer, you can just do:
```
git tag 3.6
git push origin 3.6
```

Thanks!
Jon

**Comment by sgladstone** [comment]
I created a new version 3.7, which is tagged in git and is also in the info.xml file.

**Comment by PalanteJon** [comment]
Thank you Sarah!
