### ISSUE TITLE
Checksum expiration date

### ISSUE THREAD

**Issue by magnolia61** [sgladstone/com.pogstone.fancytokens#16]
Hi Sarah,
I have been playing to get a checksum expiration date 'token' working through smarty.
I did not succeed. But maybe it would be easy for you to create a token with:
the current date + the checksum lifespan.
So in emails to edit a profile we can use something like:
You can use the links in this email to edit your data until September 20th.
Maybe it's harder than I think to create, but maybe it's a 5 minute thing for you :-)

**Comment by sgladstone** [comment]
This has been done in https://github.com/sgladstone/com.pogstone.fancytokens/releases/tag/5.0

Its in the "dates" section when you are inserting a token.

In a CiviCRM message template it will look like:   {dates.checksum_expiration}
