### ISSUE TITLE
Casual Joint Greeting Tokens not evaluating gender

### ISSUE THREAD

**Issue by yosefromano** [sgladstone/com.pogstone.fancytokens#18]
When using Formal joint tokens (those that include the individual prefix), the gender is evaluated to put the male first in the greeting (i.e. Mr. & Mrs. Smith). However, Casual joint tokens (those that exclude the individual prefix) put contact_a of the relationship as the first in the greeting regardless of the contact's gender or title. The only workaround is to delete the relationships where the husband is contact_b and recreate them.

Ideally, all joint tokens should evaluate the gender in order to put the male first. 
As far as I can tell, it should be pretty straightforward to fix this by simply copying the conditionals used in formal joint greeting tokens to the casual joint greeting tokens. 
Happy to chip in for a fix

Here are some screenshots from some tests I ran.

<img width="741" alt="screen shot 2017-12-10 at 1 25 05 pm" src="https://user-images.githubusercontent.com/10218159/33809693-bb3a1600-ddaf-11e7-8716-d2e7a8bb2260.png">
<img width="752" alt="screen shot 2017-12-10 at 1 24 16 pm" src="https://user-images.githubusercontent.com/10218159/33809694-bb5534b2-ddaf-11e7-9ef3-9e25a59c944c.png">
<img width="724" alt="screen shot 2017-12-10 at 1 29 12 pm" src="https://user-images.githubusercontent.com/10218159/33809691-bb06e578-ddaf-11e7-81ab-3881d0533207.png">
<img width="740" alt="screen shot 2017-12-10 at 1 27 40 pm" src="https://user-images.githubusercontent.com/10218159/33809692-bb1fc688-ddaf-11e7-8d60-23050378f9b9.png">

**Comment by philmb** [comment]
It is a cultural thing, and I can see why some might find this an important issue. But, I do not find it ideal to force the male name to be first. Not to mention that in our dataset there are spouse relationships with two males or two females.

**Comment by sgladstone** [comment]
This would need to be configurable, as different organizations have different preferences.   Also, a simple solution would be to use the formal tokens. In the case of a couple, the token would put "Mr." at the beginning.
