### ISSUE TITLE
Tokens for registration pages not resolving if event is not public

### ISSUE THREAD

**Issue by philmb** [sgladstone/com.pogstone.fancytokens#19]
Tokens are available in the token list for upcoming events that are not Public. This makes sense to me.

However, those tokens are blank, which is not the expected result.

There are two possible approaches:

- Simply don't make non-Public events available in the token list. I don't prefer this, as there are many reasons one might want to send emails to register for an event while not having that event listed publicly.

- Make these tokens resolve as expected.

**Comment by sgladstone** [comment]
This has been dealt with in https://github.com/sgladstone/com.pogstone.fancytokens/releases/tag/4.1
