### ISSUE TITLE
Formal tokens making wrong assumptions about gender

### ISSUE THREAD

**Issue by philmb** [sgladstone/com.pogstone.fancytokens#20]
When a contact in a spousal relationship does not have a specified gender or prefix, the gender is assumed to be male: {greetings.joint_formal} and {greetings.joint_formal_firstname} resolve to "Mr. and Mr. LastName" and "Mr. First Last and Mr. First Last".

In a world of gender complexity, I'd suggest that if a token encounters no explicit gender cues, that it resolve instead to FirstName LastName. At the very least, the README should explicitly describe this limitation and indicate that to use the formal greeting tokens the dataset must include gender or prefix.

**Comment by sgladstone** [comment]
This has been dealt with in https://github.com/sgladstone/com.pogstone.fancytokens/releases/tag/4.1

The new behavior:  No assumptions are made. 

If the individual contact (John Doe) does not have gender filled in as "Female" or "Male", nor has an individual prefix filled in, then the token will return "UNKNOWN PREFIX John Doe" for the formal tokens,
