### ISSUE TITLE
Replace SSL code with internal calls

### ISSUE THREAD

**Issue by MegaphoneJon** [sgladstone/com.pogstone.fancytokens#21]
Hi Sarah,

Thanks for a new version of your excellent extension!

I was just reviewing the code as part of my maintenance contract for a client, and I saw that you call `$_SERVER['HTTPS']` to determine if HTTPS is in use.

However, this only determines if the current user is using SSL, not if SSL is the preferred protocol.  Instead, I think you can replace a whole lot of that code with a call to `CRM_Core_Config::singleton()->userSystem->getAbsoluteBaseURL()`.

Since that code is Drupal-specific, you might even get away with a Drupal-specific call to `url()` but I suspect that would break on D8, whereas this approach would work for any non-CiviCRM URL on the site.  I think it'll also help with multi-site edge cases.

**Comment by sgladstone** [comment]
In most places,  I was previously using the CiviCRM function
CRM_Utils_System::url( )  

There was one section (for Drupal webforms) where I was not, and I cleaned up that code to use CRM_Utils_System::url() there as well.       Please try out version 5.1:
https://github.com/sgladstone/com.pogstone.fancytokens/releases/tag/5.1
