### ISSUE TITLE
Please tag 3.0 release

### ISSUE THREAD

**Issue by colemanw** [sgladstone/com.pogstone.fancytokens#3]
I have updated https://civicrm.org/extensions/fancy-tokens with "ready for automated distribution" and added the git url. So now if you tag the 3.0 release it will automatically create and publish a release at civicrm.org and users will be able to download and install the extension in-app.

**Comment by sgladstone** [comment]
This is done. release 3.0 is now tagged.  (I also updated the page at https://civicrm.org/extensions/fancy-tokens )
