### ISSUE TITLE
Proposal to move this ext to Gitlab so that it can be community-maintained (PHP8 support)

### ISSUE THREAD

**Issue by mlutfy** [sgladstone/com.pogstone.fancytokens#30]
Hi @sgladstone, I would like to move this extension to CiviCRM's Gitlab, so that we can minimally maintain things such as PHP8 support. You would still have maintainer access, but other people could help fix bugs and publish new releases.

Do you have any plans for this extension? Any objections?

**Comment by kapn1966** [comment]
Looks like she hasn't been here since Dec 3, 2022. Probably safe to go ahead.

**Comment by mlutfy** [comment]
Done: https://lab.civicrm.org/extensions/fancytokens/-/tree/master
