### ISSUE TITLE
Tokens not selectable in civicrm 4.5 drupal 7.3.4

### ISSUE THREAD

**Issue by magnolia61** [sgladstone/com.pogstone.fancytokens#5]
Hello Sarah, For the last months we experience a problem with the fancytokens extension on civicrm 4.5. When we activate it, the token selector blanks out (see attached screenshot). Do you have a clue on how we can get it working? We've grown fond of it :)
![civicrm_fancytokens_problem](https://cloud.githubusercontent.com/assets/2195908/6245164/e1e5e09a-b75b-11e4-9b94-33fd531c54ed.png)

**Comment by magnolia61** [comment]
With the 4.6 in beta since today i was wondering if you have plans for 4.5 and 4.6 compatibility. 
Of course I will also try and test myself, but you know the architecture of the extension and changes in civicrm better than I do :-)

**Comment by sgladstone** [comment]
I have a new version that works with 4.5. I will update github soon

**Comment by sgladstone** [comment]
When I double-checked the version in GitHub and compared it to my local version for CiviCRM version 4.5.x, they already match.   Make sure you are running version 3.0 of my extension

**Comment by sgladstone** [comment]
BTW: Version 3.0 of this extension should work with both versions 4.5.x and 4.6.x. (I need to test with version 4.6, but I do not anticipate any issues for 4.6)
