### ISSUE TITLE
Release for 4.6?

### ISSUE THREAD

**Issue by colemanw** [sgladstone/com.pogstone.fancytokens#6]
Very little has changed in CiviCRM 4.5 to 4.6 wrt tokens, so I suspect you could just tag and release a 4.6-compatible version without any updates (but haven't tried it myself).

**Comment by sgladstone** [comment]
I updated the info.xml so that it lists version 4.6, and also tagged this new version. (I have not done any testing on 4.6 though)

**Comment by sgladstone** [comment]
I also added the latest version (3.1) which supports 4.6 to the CiviCRM extensions directory. See https://civicrm.org/extensions/fancy-tokens

**Comment by colemanw** [comment]
Thanks. BTW did you have to manually create the release on civicrm.org? I thought it was supposed to do that automatically these days. Hope that feature is still working.

**Comment by sgladstone** [comment]
I created the new release on civicrm.org manually. I didn't know anything had been automated. (BTW: How does the automation know which tags/branches on GitHub to grab? Is there anything special I need to do on GitHub?

**Comment by colemanw** [comment]
According to [this page](http://wiki.civicrm.org/confluence/display/CRMDOC/Publish+an+Extension) you simply need to create a tag in git and it will be automatically published that day.

**Comment by sgladstone** [comment]
After reading that page, I am confused about 2 things:
 a) Why is this extension published (at https://civicrm.org/extdir/ver=4.6.3%7Ccms=Drupal) but not one of my other extensions ( https://github.com/sgladstone/com.pogstone.contenttokens/tree/3.0 ) 

b) In the page you sent me to (http://wiki.civicrm.org/confluence/display/CRMDOC/Publish+an+Extension) , in the section "Publish a CiviCRM extension (Recommended Process)" ... "How to publish subsequent releases:"   It says to OMIT the <develStage> tag. However, in the section "Eligibility for Automated Distribution"  it says the the <develStage> tag is REQUIRED. Which is it?
