### ISSUE TITLE
PHP error: "Call to undefined function" module_exists( "webform_civicrm")

### ISSUE THREAD

**Issue by shawnholt** [sgladstone/com.pogstone.fancytokens#7]
On 4.6.7 I get error in /modules/civicrm/extern/error_log

 PHP Fatal error:  Call to undefined function module_exists() in /civicrm/extensions/com.pogstone.fancytokens-master/fancytokens.php on line 103

Scope issue with drupal API  Also strange statement no?
		if( module_exists( "webform_civicrm") && module_exists( "webform_civicrm"))

**Comment by sgladstone** [comment]
What version of Drupal are you using?

**Comment by colemanw** [comment]
There may be certain edge cases where drupal is not bootstrapped e.g. via cli calls.
I would suggest this change:
https://github.com/sgladstone/com.pogstone.fancytokens/pull/9

**Comment by sgladstone** [comment]
This is fixed in version/branch 3.5.      Is there documentation somewhere that lists when the CMS is not bootstrapped when using CiviCRM via CLI (or some other entry point) ?
